### ISSUE TITLE
Manually set Addresses in the HA addons

### ISSUE THREAD

**Issue by maxi1134** [delfick/photons-homeassistant#3]
Hi there,
I hope you are good!

I installed this addon in hope of being able to stop the effect on my LIFX tile sets!
It seems to work so far, although I am encountering a bit of an issue, some tile sets are Vlaned(As they all should be soon).

I did read the docs and found a way to run this command inside the docker shell: 

1:` root@ae9861ff-photons-interactor:/data# export HARDCODED_DISCOVERY='{"d073d5******": "192.168.20.**", "d073d5******": "192.168.0.**"}'  `
Folloded by: ` lifx lan:find_ips -- '{"env_output": true}'   `
Unfortunately, this does not seem to work.

My idea, a way to manually set addresses in the HA addon, that way we can hardcode the LIFX tiles.

Would that be a possibility?

Have a great day!

**Comment by delfick** [comment]
in what way doesn't it work?

Also, you can put in /data a lifx.yml with the format shown in https://photons.delfick.com/configuration/discovery_options.html

lifx from the cli will look for lifx.yml in the current directory by default. And the interactor will look for it in /data by default, https://photons.delfick.com/apps/interactor/options.html

**Comment by maxi1134** [comment]
Thanks for the prompt answer!

It seems to only detect the lights in the same Vlan.

I will try that trick right now and let you know if it works!

**Comment by maxi1134** [comment]
That did it!

Thanks a lot for this tool by the way, been looking for a way to stop the effects on the tiles for 2 years now!

**Comment by delfick** [comment]
woot!
