### ISSUE TITLE
Install and Update Error

### ISSUE THREAD

**Issue by joshua-pe** [delfick/photons-homeassistant#6]
Hey,
I recently came across an issue that is preventing all updates or installs of the new 14.0 release.  

An image is attached of the error. I tried having a quick look into what would be causing this but wasn't able to determine anything, only thing that stands out is the missing 'b' from the /bin/bash command at the start.

Thanks in advance. 

![image](https://github.com/delfick/photons-homeassistant/assets/63589370/65d426b0-7587-412e-aa1b-dd37b3728211)

**Comment by delfick** [comment]
I'm unsure where that comes from, I'm not sure it's photons related. @Djelibeybi do you know where this might be misconfigured?

**Comment by Djelibeybi** [comment]
I can reproduce this locally, so I'll work out why the upstream base image doesn't like `pip` and submit a fix once I find it.

**Comment by delfick** [comment]
should @Final-Hawk try again now that's merged @Djelibeybi ?

**Comment by Djelibeybi** [comment]
Yep. @Final-Hawk : you will need to remove the repo from the addon store first, then add it again so that Home Assistant downloads the latest commit instead of using its cached copy.

**Comment by joshua-pe** [comment]
That's all working now. Thank you guys so much!

**Comment by delfick** [comment]
wooh!
